/**
 * Exports a CaptionAI edit as an editable project for After Effects and
 * Premiere Pro.
 *
 * After Effects: a `.jsx` ExtendScript that rebuilds the comp — footage layer,
 * one text layer per caption block, styling, and the same in/out transitions
 * used in the preview.
 *
 * Premiere Pro: a `.zip` containing an FCP7 (`xmeml`) sequence Premiere imports
 * natively, an `.srt` caption track, and a short README. Premiere's `.prproj`
 * container is a closed binary format, so `xmeml` is the interchange route
 * Adobe itself documents.
 */

export type NleWord = { text: string; start: number; end: number; color?: string; font?: string };

export type NleBlock = {
  words: NleWord[];
  /** ms on the edited (post-cut) timeline */
  start: number;
  end: number;
};

export type NleStyle = {
  fontFamily: string;
  fontSizePx: number;
  color: string;
  strokeColor?: string;
  strokeWidth?: number;
  uppercase?: boolean;
  align: "center" | "bottom";
};

export type NleProject = {
  name: string;
  width: number;
  height: number;
  fps: number;
  durationMs: number;
  videoFileName: string;
  blocks: NleBlock[];
  style: NleStyle;
  transition: "none" | "fade" | "pop" | "rise" | "slide";
};

const IN_MS = 220;
const OUT_MS = 160;

function esc(s: string) {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\r?\n/g, " ");
}

function xmlEsc(s: string) {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function hexToRgbTriplet(hex: string): [number, number, number] {
  const m = /^#?([0-9a-f]{6})$/i.exec(hex.trim());
  if (!m) return [1, 1, 1];
  const n = parseInt(m[1], 16);
  return [((n >> 16) & 255) / 255, ((n >> 8) & 255) / 255, (n & 255) / 255];
}

function blockText(b: NleBlock, uppercase?: boolean) {
  const t = b.words.map((w) => w.text).join(" ");
  return uppercase ? t.toUpperCase() : t;
}

/** Builds an ExtendScript that recreates the captioned edit in After Effects. */
export function buildAeJsx(p: NleProject): string {
  const [r, g, b] = hexToRgbTriplet(p.style.color);
  const [sr, sg, sb] = hexToRgbTriplet(p.style.strokeColor ?? "#000000");
  const durSec = Math.max(1, p.durationMs / 1000);

  const layers = p.blocks
    .map((blk, i) => {
      const txt = esc(blockText(blk, p.style.uppercase));
      const inS = (blk.start / 1000).toFixed(3);
      const outS = (Math.max(blk.end, blk.start + 200) / 1000).toFixed(3);
      const inEnd = ((blk.start + IN_MS) / 1000).toFixed(3);
      const outStart = ((Math.max(blk.end, blk.start + 200) - OUT_MS) / 1000).toFixed(3);
      return `
  // ---- caption ${i + 1} ----
  var t${i} = comp.layers.addText("${txt}");
  t${i}.startTime = 0;
  t${i}.inPoint = ${inS};
  t${i}.outPoint = ${outS};
  styleText(t${i});
  t${i}.property("Transform").property("Position").setValue([comp.width / 2, capY]);
  applyTransition(t${i}, ${inS}, ${inEnd}, ${outStart}, ${outS});`;
    })
    .join("\n");

  return `// ${p.name} — generated by ZentryQor CaptionAI
// Run with File > Scripts > Run Script File… in After Effects.
// Put "${p.videoFileName}" next to this script (or relink when prompted).
(function () {
  app.beginUndoGroup("CaptionAI import");

  var comp = app.project.items.addComp(
    "${esc(p.name)}",
    ${p.width},
    ${p.height},
    1,
    ${durSec.toFixed(3)},
    ${p.fps}
  );

  // Footage — relinks automatically when the clip sits beside this script.
  try {
    var f = new File(File($.fileName).path + "/${esc(p.videoFileName)}");
    if (f.exists) {
      var io = new ImportOptions(f);
      var footage = app.project.importFile(io);
      var vl = comp.layers.add(footage);
      vl.moveToEnd();
    }
  } catch (e) {}

  var capY = ${p.style.align === "center" ? "comp.height / 2" : "comp.height * 0.86"};
  var transition = "${p.transition}";

  function styleText(layer) {
    var doc = layer.property("Source Text").value;
    doc.font = "${esc(p.style.fontFamily)}";
    doc.fontSize = ${Math.round(p.style.fontSizePx)};
    doc.fillColor = [${r.toFixed(4)}, ${g.toFixed(4)}, ${b.toFixed(4)}];
    doc.applyFill = true;
    ${
      p.style.strokeWidth
        ? `doc.applyStroke = true;
    doc.strokeColor = [${sr.toFixed(4)}, ${sg.toFixed(4)}, ${sb.toFixed(4)}];
    doc.strokeWidth = ${Math.round(p.style.strokeWidth)};
    doc.strokeOverFill = false;`
        : `doc.applyStroke = false;`
    }
    doc.justification = ParagraphJustification.CENTER_JUSTIFY;
    layer.property("Source Text").setValue(doc);
  }

  function applyTransition(layer, tIn, tInEnd, tOutStart, tOut) {
    if (transition === "none") return;
    var op = layer.property("Transform").property("Opacity");
    op.setValueAtTime(tIn, 0);
    op.setValueAtTime(tInEnd, 100);
    op.setValueAtTime(tOutStart, 100);
    op.setValueAtTime(tOut, 0);

    if (transition === "pop") {
      var sc = layer.property("Transform").property("Scale");
      sc.setValueAtTime(tIn, [78, 78]);
      sc.setValueAtTime(tInEnd, [100, 100]);
      easeIn(sc);
    } else if (transition === "rise" || transition === "slide") {
      var pos = layer.property("Transform").property("Position");
      var base = pos.value;
      var off = transition === "rise"
        ? [base[0], base[1] + ${Math.round(p.style.fontSizePx * 0.6)}]
        : [base[0] - ${Math.round(p.width * 0.06)}, base[1]];
      pos.setValueAtTime(tIn, off);
      pos.setValueAtTime(tInEnd, base);
      easeIn(pos);
    }
    easeIn(op);
  }

  function easeIn(prop) {
    try {
      for (var k = 1; k <= prop.numKeys; k++) {
        prop.setInterpolationTypeAtKey(k, KeyframeInterpolationType.BEZIER, KeyframeInterpolationType.BEZIER);
      }
    } catch (e) {}
  }
${layers}

  comp.openInViewer();
  app.endUndoGroup();
})();
`;
}

function srtTime(ms: number) {
  const t = Math.max(0, Math.round(ms));
  const h = Math.floor(t / 3600000);
  const m = Math.floor((t % 3600000) / 60000);
  const s = Math.floor((t % 60000) / 1000);
  const msr = t % 1000;
  const p2 = (n: number) => String(n).padStart(2, "0");
  return `${p2(h)}:${p2(m)}:${p2(s)},${String(msr).padStart(3, "0")}`;
}

export function buildSrt(p: NleProject): string {
  return p.blocks
    .map((b, i) => {
      const end = Math.max(b.end, b.start + 300);
      return `${i + 1}\n${srtTime(b.start)} --> ${srtTime(end)}\n${blockText(b, p.style.uppercase)}\n`;
    })
    .join("\n");
}

/** FCP7 xmeml sequence — Premiere Pro imports this as an editable sequence. */
export function buildPremiereXml(p: NleProject): string {
  const fps = Math.round(p.fps);
  const frames = Math.max(1, Math.round((p.durationMs / 1000) * fps));
  const markers = p.blocks
    .map(
      (b, i) => `        <marker>
          <name>${xmlEsc(blockText(b, p.style.uppercase))}</name>
          <comment>caption ${i + 1}</comment>
          <in>${Math.round((b.start / 1000) * fps)}</in>
          <out>${Math.round((Math.max(b.end, b.start + 300) / 1000) * fps)}</out>
        </marker>`,
    )
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xmeml>
<xmeml version="5">
  <sequence id="captionai-seq">
    <name>${xmlEsc(p.name)}</name>
    <duration>${frames}</duration>
    <rate><timebase>${fps}</timebase><ntsc>FALSE</ntsc></rate>
    <media>
      <video>
        <format>
          <samplecharacteristics>
            <rate><timebase>${fps}</timebase><ntsc>FALSE</ntsc></rate>
            <width>${p.width}</width>
            <height>${p.height}</height>
          </samplecharacteristics>
        </format>
        <track>
          <clipitem id="clip-1">
            <name>${xmlEsc(p.videoFileName)}</name>
            <duration>${frames}</duration>
            <rate><timebase>${fps}</timebase><ntsc>FALSE</ntsc></rate>
            <start>0</start>
            <end>${frames}</end>
            <in>0</in>
            <out>${frames}</out>
            <file id="file-1">
              <name>${xmlEsc(p.videoFileName)}</name>
              <pathurl>./${xmlEsc(p.videoFileName)}</pathurl>
              <rate><timebase>${fps}</timebase><ntsc>FALSE</ntsc></rate>
              <duration>${frames}</duration>
              <media>
                <video>
                  <samplecharacteristics>
                    <width>${p.width}</width>
                    <height>${p.height}</height>
                  </samplecharacteristics>
                </video>
                <audio><channelcount>2</channelcount></audio>
              </media>
            </file>
          </clipitem>
        </track>
      </video>
      <audio>
        <track>
          <clipitem id="clip-1-a">
            <name>${xmlEsc(p.videoFileName)}</name>
            <file id="file-1" />
            <start>0</start>
            <end>${frames}</end>
            <in>0</in>
            <out>${frames}</out>
          </clipitem>
        </track>
      </audio>
    </media>
${markers}
  </sequence>
</xmeml>
`;
}

export function buildPremiereReadme(p: NleProject): string {
  return `${p.name} — Premiere Pro package (ZentryQor CaptionAI)

Files
  sequence.xml   FCP7 (xmeml) sequence: ${p.width}x${p.height} @ ${p.fps}fps, clip + caption markers
  captions.srt   caption blocks (max 3 words each), matching the preview timing
  README.txt     this file

How to open
  1. Put your source clip ("${p.videoFileName}") in this folder.
  2. Premiere Pro > File > Import… > sequence.xml (relink the clip if asked).
  3. File > Import… > captions.srt, then drag it onto the sequence to get a
     live caption track you can restyle in the Text panel.
  4. Text panel > Captions > "Upgrade to graphics" if you want per-caption
     transitions and effects as Essential Graphics layers.

Notes
  Premiere's .prproj is a closed binary format, so Adobe's documented
  interchange route (xmeml + SRT) is used instead. Everything stays editable.
  Style used: ${p.style.fontFamily}, ${Math.round(p.style.fontSizePx)}px, ${p.style.color}${
    p.style.strokeWidth ? `, stroke ${p.style.strokeWidth}px ${p.style.strokeColor}` : ""
  }, transition "${p.transition}".
`;
}

export function downloadTextFile(name: string, content: string, type = "text/plain") {
  const url = URL.createObjectURL(new Blob([content], { type }));
  const a = document.createElement("a");
  a.href = url;
  a.download = name;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 4000);
}

export async function downloadPremierePackage(p: NleProject) {
  const { default: JSZip } = await import("jszip");
  const zip = new JSZip();
  zip.file("sequence.xml", buildPremiereXml(p));
  zip.file("captions.srt", buildSrt(p));
  zip.file("README.txt", buildPremiereReadme(p));
  const blob = await zip.generateAsync({ type: "blob" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${p.name.replace(/[^\w.-]+/g, "-")}-premiere.zip`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 4000);
}
